yusakapon/dydx-chrome-extension

app/src/store/modules/order.ts, app/src/store/types.ts
* 指値注文用のaction追加
* 全注文キャンセル、個別キャンセル用action追加
指値注文
```
dispatch("order/limitOrder", {
market: Market.BTC_USD,
side: OrderSide.SELL,
size: 0.001,
price: 50000,
postOnly: true,
timeInForce: TimeInForce.GTT,
expireSecond: 100,
});
```
全注文キャンセル(全通貨)
```
dispatch("order/cancelAll");
```
全注文キャンセル(通貨指定)
```
dispatch("order/cancelAll", {
market: Market.BTC_USD,
});
```
注文キャンセル(注文指定)
```
dispatch("order/cancel", {
orderId: "11111aaaa",
});
```
https://github.com/yusakapon/dydx-chrome-extension/issues/7
=> [Store]Send limit order request #7

app/src/main.ts, app/src/store/index.ts, app/src/store/lib/ws/account.ts, app/src/store/modules/account.ts, app/src/store/types.ts
* コンポーネントでstoreの型を使えるように対応
* gettersでは型参照できないみたい... 
* 注文・ポジション情報をwsから構築するstoreを作成
*  initClient内で初期化しています
https://github.com/yusakapon/dydx-chrome-extension/issues/15
=> [Store]Create account data with websocket #15

app/src/store/index.ts, app/src/store/modules/market.ts, app/src/store/modules/orderbook.ts, app/src/store/types.ts
* `initClient`, `initMarket `の結果をbooleanで返すように変更
* エラーメッセージはstateに保存
```ts
// example
import { useStore } from "@/store";
import { Market } from "@dydxprotocol/v3-client";
const store = useStore();
const initClient = async () => {
const result = await store.dispatch("initClient");
console.log(result);
};
const initMarket = async () => {
const result = await store.dispatch("initMarket", { market: Market.BTC_USD });
console.log(result);
};
const errorMsg = computed(() => store.getters.errorMsg);
const ethAddress = computed(() => store.getters.ethAddress);
const minOrderSize = computed(() => store.getters["market/minOrderSize"]);
const bestAskPrice = computed(() => store.getters["orderbook/bestAskPrice"]);
const orders = computed(() => store.getters["account/orders"]);
const positions = …
```
=> [Store]Return value implementation during authentication #22

app/package-lock.json, app/package.json, app/src/store/index.ts, app/src/store/modules/market.ts, app/src/store/modules/order.ts, app/src/store/modules/setting.ts, app/src/store/types.ts
* market storeのactionは引数取るように変更
* 設定用storeを追加
```ts
// example
// actions
// MarketOrder Amount
const saveMarketOrderAmount = () => {
store.dispatch("setting/saveMarketOrderAmount", {
market: Market.BTC_USD,
setValue: [1, 2, 3],
});
};
// MarketOrder Leverage
const saveMarketOrderLeverage = () => {
store.dispatch("setting/saveMarketOrderLeverage", {
market: Market.BTC_USD,
setValue: [5, 10],
});
};
// LimitOrder Amount
const saveLimitOrderAmount = () => {
store.dispatch("setting/saveLimitOrderAmount", {
market: Market.BTC_USD,
setValue: [10, 20, 30],
});
};
// LimitOrder Leverage
const saveLimitOrderLeverage = () => {
store.dispatch("setting/saveLimitOrderLeverage", {
market: Market.BTC_USD,
setValue: [2, 5],
});
};
// LimitOrder Price
const saveLimitOrderPrice = () => { …
```
=> [Store] Create save setting store #25

app/src/store/modules/order.ts
* オーダー関係actionに返り値を設定
```
// 成功時
{
"result": true,
"message": "success"
}
```
```
// エラー時
{
"result": false,
"message": "order would put account below collateralization"
}
```
https://github.com/yusakapon/dydx-chrome-extension/issues/27　
=> [Store]Return value implementation during order #27

app/src/App.vue, app/src/components/ConnetWallet.vue, app/src/components/MarketOrder.vue, app/src/components/TradeHeader.vue, app/src/components/TradeInfo.vue, app/src/components/parts/AmountClose.vue, app/src/components/parts/AmountLeverage.vue, app/src/components/parts/AmountSelector.vue
- Trade Info作成
- position表示
- Market Order作成
- パーツを別コンポーネントに分離
- Market Order機能作成
#24
=> [Component] Implement market order and trade info #24

app/src/components/TradeHeader.vue
* bestbid bestaskの表示
https://github.com/yusakapon/dydx-chrome-extension/issues/39
=> Display bestbid bestask #39

app/src/store/index.ts, app/src/store/lib/ws/markets.ts, app/src/store/modules/market.ts, app/src/store/types.ts
* マーケット情報をWSで更新するように変更
https://github.com/yusakapon/dydx-chrome-extension/issues/49
=> Receive ws market channel #49

app/src/App.vue, app/src/components/LimitOrder.vue, app/src/components/MarketOrder.vue, app/src/components/parts/AmountLeverage.vue, app/src/components/parts/AmountSelector.vue, app/src/components/parts/OrderPrice.vue, app/tailwind.config.js
=> Add Limit Order Amount function #33

app/package-lock.json, app/package.json, app/src/App.vue, app/src/main.ts
=> Fix modal not moving off screen #31

app/src/store/modules/account.ts, app/src/store/modules/market.ts
* 未実現損益のリアルタイム表示に対応
https://github.com/yusakapon/dydx-chrome-extension/issues/50
=> Change unrealizedPL dynamically #50

app/src/components/TradeInfo.vue
- orderに下記機能を追加
- tbodyスクロール可
- orderのstatusにより色を分ける
- 全キャンセル機能
- オーダー数表示
=> Improvement Order Information #56

app/src/components/TradeInfo.vue
=> Trade Info does not update when changing currency #34

.github/workflows/ci-test.yml
CI research and implementation
=> CI research and implementation

app/package-lock.json, app/package.json, app/src/components/TradeHeader.vue
* 完全に動的にするのは無理だった
* 使用ライブラリを更新して最近追加された通貨に対応
* なぜかdydxに存在しない通貨もたくさん定義されていたため、APIから取得したデータにも存在する通貨のみ選択可能にした
https://github.com/yusakapon/dydx-chrome-extension/issues/48
=> Fix to automatically respond to currency increases #48

app/src/components/TradeInfo.vue
- orderに下記機能を追加
- orderの4個目を見切れさせる
- orderなし時の文言追加
- sideの配色を追加
- statusを削除
- marketを追加
- 高さを固定
- positionに下記機能を追加
- positionなし時の文言追加
- sideの配色を追加
- 高さを固定
#63
=> Adjustment of the layout of the order display section #63

app/package-lock.json, app/package.json, app/src/App.vue, app/src/components/ConnetWallet.vue, app/src/components/DisplayAddress.vue, app/src/store/index.ts, app/src/store/types.ts
* 接続中ウォレットアドレスを表示
* 認証情報をセッションに保存
* セッションに認証情報がある場合、署名なしでそれを使用するように
* ログアウト機能の追加
https://github.com/yusakapon/dydx-chrome-extension/issues/58
https://github.com/yusakapon/dydx-chrome-extension/issues/59
https://github.com/yusakapon/dydx-chrome-extension/issues/60
=> Display wallet address #58 / Fixed to be able to reload extensions #59 / Fixed to store authentication information in local storage #60

app/src/components/LimitOrder.vue, app/src/components/parts/ExpireSecond.vue
- expiration timeを設定するinput追加
#72
=> The expiration time of the limit order is 100 seconds #72

app/src/components/LimitOrder.vue
=> Fix a bug in self input #76

app/src/components/TradeInfo.vue
* All Marketsのチェックボックス追加
* チェックで全通貨ポジション・オーダー表示
* チェック時、All Cancel は全通貨のオーダーをキャンセルするように
* ついでに対応 
* [When switching currencies, only the Position update is slow. #85](https://github.com/yusakapon/dydx-chrome-extension/issues/85)
* [TypeError: Cannot read properties of undefined (reading 'market') #79](https://github.com/yusakapon/dydx-chrome-extension/issues/79)
https://github.com/yusakapon/dydx-chrome-extension/issues/37 https://github.com/yusakapon/dydx-chrome-extension/issues/79 https://github.com/yusakapon/dydx-chrome-extension/issues/85
=> Add option to trade info to display information for all currencies #37

app/src/components/DisplayAddress.vue, app/src/components/TradeInfo.vue, app/src/store/index.ts
* オーダーの注文価格を編集可能に
* TestNet MainNetの表示を追加
https://github.com/yusakapon/dydx-chrome-extension/issues/66
=> Fix to allow editing of orders (UI) #66

Dockerfile, app/bin/adjust-dist.sh, app/package.json, app/vue.config.js
https://github.com/yusakapon/dydx-chrome-extension/issues/82
ホットリロードにより、コードの変更が自動的に画面反映されるようにしました。
`npm run build`実行により、以降は変更が監視されるようになります。
初期環境構築時 もしくはmanifest.json, loader.jsに変更がある場合は、`npm run generate`を実行してください。
=> Hot Reload Research and Implementation

app/src/components/LimitOrder.vue, app/src/components/MarketOrder.vue, app/src/components/TradeHeader.vue, app/src/components/TradeInfo.vue, app/src/components/parts/AmountClose.vue, app/src/components/parts/AmountSelector.vue, app/src/components/parts/OrderPrice.vue
=> Position and order information is not displayed when login in after logout. #84

app/src/components/LimitOrder.vue
* auto limit orderは各bestpriceを使用するように変更した
https://github.com/yusakapon/dydx-chrome-extension/issues/94
=> The order price for auto limit order is wrong #94

app/src/App.vue, app/src/components/ErrorMessage.vue, app/src/components/LimitOrder.vue, app/src/components/MarketOrder.vue
- orderのエラーメッセージを枠内に表示
- orderのエラーキャッチ方法を修正
- エラーメッセージのバツを押下時
- エラー後の正常注文が通った時
#35
=> Display message in case of order error #35

app/src/components/LimitOrder.vue, app/src/components/MarketOrder.vue, app/src/components/TradeHeader.vue, app/src/components/parts/AmountSelector.vue, app/src/components/parts/OrderPrice.vue
* 最小注文数、注文数最小ステップ、呼び値を通貨毎に動的に変更
* 軽微な不具合修正
https://github.com/yusakapon/dydx-chrome-extension/issues/44
=> Dynamic rounding digits, etc. for each currency #44

app/src/App.vue
* ロゴの追加
* ファイルの読み込みが面倒そうだったのでインラインsvgで挿入
https://github.com/yusakapon/dydx-chrome-extension/issues/108
=> Add logo to header #108

app/src/components/LimitOrder.vue, app/src/components/MarketOrder.vue, app/src/components/parts/AmountInput.vue
- Amountのデザイン変更
- Amountのinputパーツを外部化
- 数値入力計算を修正
#75 #101 #97
=> Adjusting the display of Currency <-> USD #75 #101

app/src/components/LimitOrder.vue, app/src/components/parts/OrderPrice.vue
* 指値注文の価格設定部分をわかりやすくした
* 自動設定とself設定を明確に
* その他いろいろ調整
https://github.com/yusakapon/dydx-chrome-extension/issues/77
=> Improvement of UI for self input #77

app/Disclaimer.md, app/PrivacyPolicy.md, app/src/manifest.json
=> [FIX] #105 create Privacy policy and Disclaimer
